/**
 * Hide meeting/STT text in task.description for AI tasks unless the user saved it
 * (description_user_set). Matches backend app/api/v1/endpoints/tasks.py.
 */
export function taskDescriptionForDisplay(
  description: string | null | undefined,
  isAutoGenerated: boolean,
  descriptionUserSet?: boolean | null,
): string | null {
  if (!description?.trim()) return null;
  const s = description.trim();
  if (!isAutoGenerated) return s;
  if (descriptionUserSet) return s;
  return null;
}
