import {
  LayoutDashboard,
  Calendar,
  ListTodo,
  LayoutGrid,
  Users,
  BarChart3,
  Settings,
  Plus,
  Clock,
  CheckCircle2,
  AlertTriangle,
  Sparkles,
  ArrowUpRight,
  Eye,
  Loader2,
} from 'lucide-react';
import DashboardLayout from '@/components/layout/DashboardLayout';
import { SidebarItem } from '@/components/layout/Sidebar';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Avatar, AvatarFallback, AvatarImage } from '@/components/ui/avatar';
import { mockKanbanColumns, mockTeamMembers } from '@/data/mockData';
import { formatDistanceToNow } from 'date-fns';
import { cn } from '@/lib/utils';
import { useParams } from 'react-router-dom';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { Task, TaskPriority, TaskStatus } from '@/lib/types';
import { loadWorkspaceTasks, saveWorkspaceTasks } from '@/lib/workspaceStorage';
import { DndContext, DragEndEvent, useDraggable, useDroppable } from '@dnd-kit/core';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Label } from '@/components/ui/label';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { useAuth } from '@/context/AuthContext';
import {
  getProject,
  createProjectTask,
  updateProjectTask,
  extractProjectTasks,
  type ApiTask,
} from '@/lib/api';

// Kairox 5 columns: To Do, In Progress, In Review, Done, Blockers
const columnColors: Record<string, string> = {
  todo: 'border-t-muted-foreground',
  in_progress: 'border-t-primary',
  in_review: 'border-t-amber-500',
  done: 'border-t-success',
  blockers: 'border-t-destructive',
};

function apiTaskToTask(a: ApiTask): Task {
  return {
    id: a.id,
    title: a.title,
    description: a.description ?? undefined,
    status: a.status,
    priority: a.priority,
    assignee_id: a.assignee_id,
    dueDate: a.due_date ? new Date(a.due_date) : undefined,
    due_date: a.due_date,
    subtasks: a.subtasks ?? undefined,
    createdAt: new Date(a.created_at),
    updatedAt: new Date(a.updated_at),
    isAutoGenerated: a.is_auto_generated,
    completedAt: a.completed_at ? new Date(a.completed_at) : undefined,
  };
}

const COLUMN_IDS: TaskStatus[] = ['todo', 'in_progress', 'in_review', 'done', 'blockers'];

const ManagerKanban = () => {
  const { workspaceId = "alpha" } = useParams();
  const { token } = useAuth();
  const basePath = `/business/manager/workspaces/${workspaceId}`;
  const [tasks, setTasks] = useState<Task[]>([]);
  const [loading, setLoading] = useState(false);
  const [extracting, setExtracting] = useState(false);
  const [createOpen, setCreateOpen] = useState(false);
  const [createStatus, setCreateStatus] = useState<TaskStatus>("todo");
  const [title, setTitle] = useState("");
  const [description, setDescription] = useState("");
  const [priority, setPriority] = useState<TaskPriority>("medium");
  const [assigneeId, setAssigneeId] = useState<string | undefined>(undefined);
  const [subtasksStr, setSubtasksStr] = useState("");
  const managerSidebarItems: SidebarItem[] = [
    { title: 'Dashboard', href: `${basePath}/dashboard`, icon: LayoutDashboard },
    { title: 'Meetings', href: `${basePath}/meetings`, icon: Calendar, badge: 3 },
    { title: 'Tasks', href: `${basePath}/tasks`, icon: ListTodo, badge: 5 },
    { title: 'Kanban Board', href: `${basePath}/kanban`, icon: LayoutGrid },
    { title: 'Team', href: `${basePath}/team`, icon: Users },
    { title: 'Analytics', href: `${basePath}/analytics`, icon: BarChart3, isPremium: true },
    { title: 'Settings', href: `${basePath}/settings`, icon: Settings },
  ];

  const fetchProjectTasks = useCallback(async () => {
    if (!token || !workspaceId) return;
    setLoading(true);
    try {
      const project = await getProject(token, workspaceId);
      setTasks((project.tasks ?? []).map(apiTaskToTask));
    } catch {
      setTasks([]);
    } finally {
      setLoading(false);
    }
  }, [token, workspaceId]);

  useEffect(() => {
    if (token && workspaceId) {
      fetchProjectTasks();
    } else {
      const fallback = mockKanbanColumns.flatMap((col) => col.tasks).map((t) => ({
        ...t,
        status: (t.status === 'in-progress' ? 'in_progress' : t.status === 'review' ? 'in_review' : t.status === 'blocked' ? 'blockers' : t.status) as TaskStatus,
      }));
      setTasks(loadWorkspaceTasks(workspaceId, fallback));
    }
  }, [workspaceId, token, fetchProjectTasks]);

  useEffect(() => {
    if (!token && tasks.length) {
      saveWorkspaceTasks(workspaceId, tasks);
    }
  }, [tasks, workspaceId, token]);

  const columns = useMemo(
    () =>
      ({
        todo: { id: 'todo' as const, title: 'To Do' },
        in_progress: { id: 'in_progress' as const, title: 'In Progress' },
        in_review: { id: 'in_review' as const, title: 'In Review' },
        done: { id: 'done' as const, title: 'Done' },
        blockers: { id: 'blockers' as const, title: 'Blockers' },
      }) satisfies Record<TaskStatus, { id: TaskStatus; title: string }>,
    [],
  );

  const tasksByStatus = useMemo(
    () =>
      COLUMN_IDS.map((status) => ({
        ...columns[status],
        tasks: tasks.filter((task) => task.status === status),
      })),
    [tasks, columns],
  );

  const handleDragEnd = async (event: DragEndEvent) => {
    const { active, over } = event;
    if (!over) return;
    const activeId = String(active.id);
    const overId = String(over.id) as TaskStatus;
    if (token && workspaceId) {
      try {
        await updateProjectTask(token, workspaceId, activeId, { status: overId });
        await fetchProjectTasks();
      } catch {
        // keep local state on error
      }
    } else {
      setTasks((prev) =>
        prev.map((task) =>
          task.id === activeId ? { ...task, status: overId, updatedAt: new Date() } : task,
        ),
      );
    }
  };

  const handleCreateTask = async () => {
    if (!title.trim()) return;
    if (token && workspaceId) {
      try {
        const subtasks = subtasksStr.trim() ? subtasksStr.split(',').map((s) => s.trim()).filter(Boolean) : undefined;
        await createProjectTask(token, workspaceId, {
          title: title.trim(),
          description: description.trim() || undefined,
          status: createStatus,
          priority,
          assignee_id: assigneeId || null,
          subtasks: subtasks ?? undefined,
        });
        await fetchProjectTasks();
        setTitle("");
        setDescription("");
        setPriority("medium");
        setAssigneeId(undefined);
        setSubtasksStr("");
        setCreateOpen(false);
      } catch {
        // keep modal open on error
      }
    } else {
      const assignee = assigneeId ? mockTeamMembers.find((m) => m.id === assigneeId) : undefined;
      const newTask: Task = {
        id: `task-${Date.now()}`,
        title: title.trim(),
        description: description.trim() || undefined,
        status: createStatus,
        priority,
        assignee,
        createdAt: new Date(),
        updatedAt: new Date(),
        isAutoGenerated: false,
      };
      setTasks((prev) => [newTask, ...prev]);
      setTitle("");
      setDescription("");
      setPriority("medium");
      setAssigneeId(undefined);
      setCreateOpen(false);
    }
  };

  const handleExtractTasks = async () => {
    if (!token || !workspaceId) return;
    setExtracting(true);
    try {
      await extractProjectTasks(token, workspaceId);
      await fetchProjectTasks();
    } finally {
      setExtracting(false);
    }
  };

  const DraggableCard = ({ task }: { task: Task }) => {
    const { attributes, listeners, setNodeRef, transform, isDragging } = useDraggable({
      id: task.id,
    });
    const style = transform
      ? { transform: `translate3d(${transform.x}px, ${transform.y}px, 0)` }
      : undefined;
    return (
      <Card
        ref={setNodeRef}
        style={style}
        {...listeners}
        {...attributes}
        className={cn(
          "shadow-sm hover:shadow-md transition-shadow cursor-pointer",
          isDragging && "opacity-60",
        )}
      >
        <CardContent className="p-3">
          <div className="flex items-start justify-between gap-2 mb-2">
            <p className="font-medium text-sm leading-snug">{task.title}</p>
            {task.isAutoGenerated && (
              <Badge
                variant="outline"
                className="text-[10px] bg-secondary/10 border-secondary/30 text-secondary flex-shrink-0"
              >
                <Sparkles className="h-2 w-2 mr-0.5" />
                AI
              </Badge>
            )}
          </div>
          <div className="flex items-center gap-2 mb-3">
            <Badge
              variant="outline"
              className={cn(
                "text-[10px]",
                task.priority === 'urgent' && 'border-destructive text-destructive bg-destructive/10',
                task.priority === 'high' && 'border-warning text-warning bg-warning/10',
                task.priority === 'medium' && 'border-primary text-primary bg-primary/10',
                task.priority === 'low' && 'border-muted-foreground'
              )}
            >
              {task.priority}
            </Badge>
            {(task.dueDate || task.due_date) && (
              <span
                className={cn(
                  "text-[10px] flex items-center gap-1",
                  new Date(task.dueDate ?? task.due_date!) < new Date() && task.status !== 'done'
                    ? 'text-destructive'
                    : 'text-muted-foreground'
                )}
              >
                {new Date(task.dueDate ?? task.due_date!) < new Date() && task.status !== 'done' ? (
                  <AlertTriangle className="h-2.5 w-2.5" />
                ) : (
                  <Clock className="h-2.5 w-2.5" />
                )}
                {formatDistanceToNow(new Date(task.dueDate ?? task.due_date!), { addSuffix: true })}
              </span>
            )}
          </div>
          <div className="flex items-center justify-between">
            {(task.assignee || task.assignee_id) && (
              <div className="flex items-center gap-2">
                {task.assignee ? (
                  <>
                    <Avatar className="h-5 w-5">
                      <AvatarImage src={task.assignee.avatar} />
                      <AvatarFallback className="text-[8px]">
                        {task.assignee.name.split(' ').map((n) => n[0]).join('')}
                      </AvatarFallback>
                    </Avatar>
                    <span className="text-[10px] text-muted-foreground">
                      {task.assignee.name.split(' ')[0]}
                    </span>
                  </>
                ) : (
                  <span className="text-[10px] text-muted-foreground">{task.assignee_id}</span>
                )}
              </div>
            )}
            {task.isAutoGenerated && (
              <span className="text-[10px] text-muted-foreground flex items-center gap-1">
                <ArrowUpRight className="h-2.5 w-2.5" />
                From Sprint Planning
              </span>
            )}
          </div>
        </CardContent>
      </Card>
    );
  };

  const DroppableColumn = ({
    status,
    title,
    columnTasks,
  }: {
    status: TaskStatus;
    title: string;
    columnTasks: Task[];
  }) => {
    const { setNodeRef } = useDroppable({ id: status });
    return (
      <div ref={setNodeRef} className="flex-shrink-0 w-72">
        <Card className={cn("shadow-card border-t-4", columnColors[status])}>
          <CardHeader className="pb-3">
            <div className="flex items-center justify-between">
              <CardTitle className="text-sm font-medium flex items-center gap-2">
                {title}
                <Badge
                  variant="secondary"
                  className="h-5 w-5 rounded-full p-0 flex items-center justify-center text-xs"
                >
                  {columnTasks.length}
                </Badge>
              </CardTitle>
              <Button
                variant="ghost"
                size="icon"
                className="h-6 w-6"
                onClick={() => {
                  setCreateStatus(status);
                  setCreateOpen(true);
                }}
              >
                <Plus className="h-4 w-4" />
              </Button>
            </div>
          </CardHeader>
          <CardContent className="space-y-3 min-h-[400px]">
            {columnTasks.map((task) => (
              <DraggableCard key={task.id} task={task} />
            ))}
            {columnTasks.length === 0 && (
              <div className="flex flex-col items-center justify-center py-8 text-center">
                <div className="h-10 w-10 rounded-full bg-muted flex items-center justify-center mb-2">
                  <CheckCircle2 className="h-5 w-5 text-muted-foreground" />
                </div>
                <p className="text-sm text-muted-foreground">No tasks here</p>
              </div>
            )}
          </CardContent>
        </Card>
      </div>
    );
  };

  return (
    <DashboardLayout
      sidebarItems={managerSidebarItems}
      sidebarTitle="Manager"
      sidebarSubtitle="Business Dashboard"
    >
      <div className="space-y-6">
        {/* Page Header */}
        <div className="flex items-center justify-between">
          <div>
            <h1 className="text-2xl font-bold">Kairox Kanban Board</h1>
            <p className="text-muted-foreground">
              To Do · In Progress · In Review · Done · Blockers. Extract tasks from meeting transcripts.
            </p>
          </div>
          <div className="flex items-center gap-2">
            {token && workspaceId && (
              <Button
                variant="outline"
                size="sm"
                onClick={handleExtractTasks}
                disabled={extracting}
              >
                {extracting ? (
                  <Loader2 className="h-4 w-4 animate-spin mr-2" />
                ) : (
                  <Sparkles className="h-4 w-4 mr-2" />
                )}
                Extract tasks from meetings
              </Button>
            )}
            <Badge variant="outline" className="bg-secondary/10 border-secondary/30 text-secondary">
              <Sparkles className="h-3 w-3 mr-1" />
              AI-Managed
            </Badge>
          </div>
        </div>
        {loading && (
          <div className="flex items-center justify-center py-8">
            <Loader2 className="h-8 w-8 animate-spin text-muted-foreground" />
          </div>
        )}

        {/* Kanban Board — 5 columns */}
        {!loading && (
        <DndContext onDragEnd={handleDragEnd}>
          <div className="flex gap-4 overflow-x-auto pb-4">
            {tasksByStatus.map((column) => (
              <DroppableColumn
                key={column.id}
                status={column.id}
                title={column.title}
                columnTasks={column.tasks}
              />
            ))}
          </div>
        </DndContext>
        )}

        {/* Legend */}
        <Card className="shadow-card">
          <CardContent className="py-4">
            <div className="flex items-center justify-between flex-wrap gap-4">
              <div className="flex items-center gap-4 text-sm">
                <span className="text-muted-foreground">Auto-move indicators:</span>
                <div className="flex items-center gap-2">
                  <Badge variant="outline" className="bg-secondary/10 border-secondary/30 text-secondary text-xs">
                    <Sparkles className="h-2.5 w-2.5 mr-1" />
                    AI Generated
                  </Badge>
                  <span className="text-muted-foreground">Task created from meeting</span>
                </div>
              </div>
              <div className="flex items-center gap-4 text-xs text-muted-foreground">
                <div className="flex items-center gap-1">
                  <div className="h-2 w-2 rounded-full bg-success" />
                  Done
                </div>
                <div className="flex items-center gap-1">
                  <div className="h-2 w-2 rounded-full bg-primary" />
                  In Progress
                </div>
                <div className="flex items-center gap-1">
                  <div className="h-2 w-2 rounded-full bg-amber-500" />
                  In Review
                </div>
                <div className="flex items-center gap-1">
                  <div className="h-2 w-2 rounded-full bg-destructive" />
                  Blockers
                </div>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>

      <Dialog open={createOpen} onOpenChange={setCreateOpen}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Create task</DialogTitle>
            <DialogDescription>Add a task scoped to this workspace.</DialogDescription>
          </DialogHeader>
          <div className="space-y-3">
            <Label htmlFor="kanban-title">Title</Label>
            <Input
              id="kanban-title"
              placeholder="Define onboarding checklist"
              value={title}
              onChange={(event) => setTitle(event.target.value)}
            />
            <Label htmlFor="kanban-description">Description</Label>
            <Textarea
              id="kanban-description"
              placeholder="Optional details..."
              value={description}
              onChange={(event) => setDescription(event.target.value)}
            />
            <div className="grid grid-cols-2 gap-2">
              <div className="space-y-2">
                <Label>Status</Label>
                <Select value={createStatus} onValueChange={(value) => setCreateStatus(value as TaskStatus)}>
                  <SelectTrigger>
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="todo">To Do</SelectItem>
                    <SelectItem value="in_progress">In Progress</SelectItem>
                    <SelectItem value="in_review">In Review</SelectItem>
                    <SelectItem value="done">Done</SelectItem>
                    <SelectItem value="blockers">Blockers</SelectItem>
                  </SelectContent>
                </Select>
              </div>
              <div className="space-y-2">
                <Label>Priority</Label>
                <Select value={priority} onValueChange={(value) => setPriority(value as TaskPriority)}>
                  <SelectTrigger>
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="low">Low</SelectItem>
                    <SelectItem value="medium">Medium</SelectItem>
                    <SelectItem value="high">High</SelectItem>
                    <SelectItem value="urgent">Urgent</SelectItem>
                  </SelectContent>
                </Select>
              </div>
            </div>
            <div className="space-y-2">
              <Label>Subtasks (comma-separated)</Label>
              <Input
                placeholder="Step 1, Step 2, ..."
                value={subtasksStr}
                onChange={(e) => setSubtasksStr(e.target.value)}
              />
            </div>
            <div className="space-y-2">
              <Label>Assignee</Label>
              <Select
                value={assigneeId ?? "unassigned"}
                onValueChange={(value) => setAssigneeId(value === "unassigned" ? undefined : value)}
              >
                <SelectTrigger>
                  <SelectValue placeholder="Unassigned" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="unassigned">Unassigned</SelectItem>
                  {mockTeamMembers.map((member) => (
                    <SelectItem key={member.id} value={member.id}>
                      {member.name}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
          </div>
          <DialogFooter>
            <Button variant="secondary" onClick={handleCreateTask} disabled={!title.trim()}>
              Add Task
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </DashboardLayout>
  );
};

export default ManagerKanban;
