import {
  LayoutDashboard,
  Calendar,
  ListTodo,
  LayoutGrid,
  FileText,
  Plus,
  Clock,
  CheckCircle2,
  AlertTriangle,
  Sparkles,
  ArrowUpRight,
} from "lucide-react";
import DashboardLayout from "@/components/layout/DashboardLayout";
import { SidebarItem } from "@/components/layout/Sidebar";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { formatDistanceToNow } from "date-fns";
import { cn } from "@/lib/utils";
import { useParams } from "react-router-dom";
import { useCallback, useEffect, useMemo, useState } from "react";
import { Task, TaskPriority, TaskStatus } from "@/lib/types";
import { useAuth } from "@/context/AuthContext";
import { getProject, updateProjectTask, createProjectTask, type ApiTask } from "@/lib/api";
import { DndContext, DragEndEvent, useDraggable, useDroppable } from "@dnd-kit/core";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";

const columnColors: Record<string, string> = {
  todo: "border-t-muted-foreground",
  in_progress: "border-t-primary",
  in_review: "border-t-amber-500",
  done: "border-t-success",
  blockers: "border-t-destructive",
};

function apiTaskToTask(a: ApiTask): Task {
  return {
    id: a.id,
    title: a.title,
    description: a.description ?? undefined,
    status: a.status,
    priority: a.priority,
    assignee_id: a.assignee_id,
    dueDate: a.due_date ? new Date(a.due_date) : undefined,
    due_date: a.due_date,
    createdAt: new Date(a.created_at),
    updatedAt: new Date(a.updated_at),
    isAutoGenerated: a.is_auto_generated,
  };
}

const TeamMemberKanban = () => {
  const { token } = useAuth();
  const { workspaceId } = useParams();
  const basePath = `/business/member/workspaces/${workspaceId}`;
  const [tasks, setTasks] = useState<Task[]>([]);
  const [memberDetails, setMemberDetails] = useState<{ id: string; name: string; email: string }[]>([]);
  const [loading, setLoading] = useState(false);
  const [createOpen, setCreateOpen] = useState(false);
  const [createStatus, setCreateStatus] = useState<TaskStatus>("todo");
  const [title, setTitle] = useState("");
  const [description, setDescription] = useState("");
  const [priority, setPriority] = useState<TaskPriority>("medium");
  const [assigneeId, setAssigneeId] = useState<string | undefined>(undefined);

  const fetchProject = useCallback(async () => {
    if (!token || !workspaceId) return;
    setLoading(true);
    try {
      const project = await getProject(token, workspaceId);
      setTasks((project.tasks ?? []).map(apiTaskToTask));
      setMemberDetails(project.member_details ?? []);
    } catch {
      setTasks([]);
      setMemberDetails([]);
    } finally {
      setLoading(false);
    }
  }, [token, workspaceId]);

  useEffect(() => {
    if (token && workspaceId) fetchProject();
  }, [fetchProject, token, workspaceId]);

  const teamMemberSidebarItems: SidebarItem[] = [
    { title: "Dashboard", href: `${basePath}/dashboard`, icon: LayoutDashboard },
    { title: "Meetings", href: `${basePath}/meetings`, icon: Calendar },
    { title: "My Tasks", href: `${basePath}/tasks`, icon: ListTodo, badge: tasks.filter((t) => t.status !== "done").length },
    { title: "Kanban", href: `${basePath}/kanban`, icon: LayoutGrid },
    { title: "Documents", href: `${basePath}/documents`, icon: FileText },
  ];

  const columns = useMemo(
    () =>
      ({
        todo: { id: "todo", title: "To Do" },
        in_progress: { id: "in_progress", title: "In Progress" },
        in_review: { id: "in_review", title: "In Review" },
        done: { id: "done", title: "Done" },
        blockers: { id: "blockers", title: "Blockers" },
      }) satisfies Record<TaskStatus, { id: TaskStatus; title: string }>,
    []
  );

  const tasksByStatus = useMemo(
    () =>
      (Object.keys(columns) as TaskStatus[]).map((status) => ({
        ...columns[status],
        tasks: tasks.filter((task) => task.status === status),
      })),
    [tasks, columns]
  );

  const handleDragEnd = async (event: DragEndEvent) => {
    const { active, over } = event;
    if (!over || !token || !workspaceId) return;
    const activeId = String(active.id);
    const overId = String(over.id) as TaskStatus;
    try {
      await updateProjectTask(token, workspaceId, activeId, { status: overId });
      setTasks((prev) =>
        prev.map((task) =>
          task.id === activeId ? { ...task, status: overId, updatedAt: new Date() } : task
        )
      );
    } catch {
      fetchProject();
    }
  };

  const handleCreateTask = async () => {
    if (!title.trim() || !token || !workspaceId) return;
    try {
      const created = await createProjectTask(token, workspaceId, {
        title: title.trim(),
        description: description.trim() || undefined,
        status: createStatus,
        priority,
        assignee_id: assigneeId || null,
      });
      setTasks((prev) => [apiTaskToTask(created), ...prev]);
      setTitle("");
      setDescription("");
      setPriority("medium");
      setAssigneeId(undefined);
      setCreateOpen(false);
    } catch {
      fetchProject();
    }
  };

  const DraggableCard = ({ task }: { task: Task }) => {
    const due = task.dueDate ?? (task as Task & { due_date?: string }).due_date;
    const { attributes, listeners, setNodeRef, transform, isDragging } = useDraggable({
      id: task.id,
    });
    const style = transform
      ? { transform: `translate3d(${transform.x}px, ${transform.y}px, 0)` }
      : undefined;
    return (
      <Card
        ref={setNodeRef}
        style={style}
        {...listeners}
        {...attributes}
        className={cn(
          "shadow-sm hover:shadow-md transition-shadow cursor-pointer",
          isDragging && "opacity-60"
        )}
      >
        <CardContent className="p-3">
          <div className="flex items-start justify-between gap-2 mb-2">
            <p className="font-medium text-sm leading-snug">{task.title}</p>
            {task.isAutoGenerated && (
              <Badge
                variant="outline"
                className="text-[10px] bg-secondary/10 border-secondary/30 text-secondary flex-shrink-0"
              >
                <Sparkles className="h-2 w-2 mr-0.5" />
                AI
              </Badge>
            )}
          </div>
          <div className="flex items-center gap-2 mb-3">
            <Badge
              variant="outline"
              className={cn(
                "text-[10px]",
                task.priority === "urgent" &&
                  "border-destructive text-destructive bg-destructive/10",
                task.priority === "high" &&
                  "border-warning text-warning bg-warning/10",
                task.priority === "medium" &&
                  "border-primary text-primary bg-primary/10",
                task.priority === "low" && "border-muted-foreground"
              )}
            >
              {task.priority}
            </Badge>
            {task.dueDate && (
              <span
                className={cn(
                  "text-[10px] flex items-center gap-1",
                  new Date(task.dueDate) < new Date() && task.status !== "done"
                    ? "text-destructive"
                    : "text-muted-foreground"
                )}
              >
                {new Date(task.dueDate) < new Date() && task.status !== "done" ? (
                  <AlertTriangle className="h-2.5 w-2.5" />
                ) : (
                  <Clock className="h-2.5 w-2.5" />
                )}
                {formatDistanceToNow(task.dueDate, { addSuffix: true })}
              </span>
            )}
          </div>
          <div className="flex items-center justify-between">
            {task.assignee_id && (() => {
              const assignee = memberDetails.find((m) => m.id === task.assignee_id);
              return assignee ? (
                <div className="flex items-center gap-2">
                  <Avatar className="h-5 w-5">
                    <AvatarFallback className="text-[8px]">{assignee.name.split(" ").map((n) => n[0]).join("")}</AvatarFallback>
                  </Avatar>
                  <span className="text-[10px] text-muted-foreground">{assignee.name.split(" ")[0]}</span>
                </div>
              ) : null;
            })()}
            {task.isAutoGenerated && (
              <span className="text-[10px] text-muted-foreground flex items-center gap-1">
                <ArrowUpRight className="h-2.5 w-2.5" />
                From meeting
              </span>
            )}
          </div>
        </CardContent>
      </Card>
    );
  };

  const DroppableColumn = ({
    status,
    title,
    columnTasks,
  }: {
    status: TaskStatus;
    title: string;
    columnTasks: Task[];
  }) => {
    const { setNodeRef } = useDroppable({ id: status });
    return (
      <div ref={setNodeRef} className="flex-shrink-0 w-72">
        <Card className={cn("shadow-card border-t-4", columnColors[status])}>
          <CardHeader className="pb-3">
            <div className="flex items-center justify-between">
              <CardTitle className="text-sm font-medium flex items-center gap-2">
                {title}
                <Badge
                  variant="secondary"
                  className="h-5 w-5 rounded-full p-0 flex items-center justify-center text-xs"
                >
                  {columnTasks.length}
                </Badge>
              </CardTitle>
              <Button
                variant="ghost"
                size="icon"
                className="h-6 w-6"
                onClick={() => {
                  setCreateStatus(status);
                  setCreateOpen(true);
                }}
              >
                <Plus className="h-4 w-4" />
              </Button>
            </div>
          </CardHeader>
          <CardContent className="space-y-3 min-h-[400px]">
            {columnTasks.map((task) => (
              <DraggableCard key={task.id} task={task} />
            ))}
            {columnTasks.length === 0 && (
              <div className="flex flex-col items-center justify-center py-8 text-center">
                <div className="h-10 w-10 rounded-full bg-muted flex items-center justify-center mb-2">
                  <CheckCircle2 className="h-5 w-5 text-muted-foreground" />
                </div>
                <p className="text-sm text-muted-foreground">No tasks here</p>
              </div>
            )}
          </CardContent>
        </Card>
      </div>
    );
  };

  return (
    <DashboardLayout
      sidebarItems={teamMemberSidebarItems}
      sidebarTitle="Team Member"
      sidebarSubtitle="Personal Workspace"
    >
      <div className="space-y-6">
        <div className="flex items-center justify-between">
          <div>
            <h1 className="text-2xl font-bold">Kanban Board</h1>
            <p className="text-muted-foreground">
              Auto-updated from meeting discussions •{" "}
              <span className="text-primary">Last sync: 2 min ago</span>
            </p>
          </div>
          <Badge
            variant="outline"
            className="bg-secondary/10 border-secondary/30 text-secondary"
          >
            <Sparkles className="h-3 w-3 mr-1" />
            AI-Synced
          </Badge>
        </div>

        <DndContext onDragEnd={handleDragEnd}>
          <div className="flex gap-4 overflow-x-auto pb-4">
            {tasksByStatus.map((column) => (
              <DroppableColumn
                key={column.id}
                status={column.id}
                title={column.title}
                columnTasks={column.tasks}
              />
            ))}
          </div>
        </DndContext>

        <Card className="shadow-card">
          <CardContent className="py-4">
            <div className="flex items-center justify-between flex-wrap gap-4">
              <div className="flex items-center gap-4 text-sm">
                <span className="text-muted-foreground">Drag cards to update status</span>
                <Badge
                  variant="outline"
                  className="bg-secondary/10 border-secondary/30 text-secondary text-xs"
                >
                  <Sparkles className="h-2.5 w-2.5 mr-1" />
                  AI Generated
                </Badge>
              </div>
              <div className="flex items-center gap-4 text-xs text-muted-foreground">
                <div className="flex items-center gap-1">
                  <div className="h-2 w-2 rounded-full bg-success" />
                  Done
                </div>
                <div className="flex items-center gap-1">
                  <div className="h-2 w-2 rounded-full bg-primary" />
                  In Progress
                </div>
                <div className="flex items-center gap-1">
                  <div className="h-2 w-2 rounded-full bg-warning" />
                  Review
                </div>
                <div className="flex items-center gap-1">
                  <div className="h-2 w-2 rounded-full bg-destructive" />
                  Blocked
                </div>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>

      <Dialog open={createOpen} onOpenChange={setCreateOpen}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Create task</DialogTitle>
            <DialogDescription>Add a task to this workspace.</DialogDescription>
          </DialogHeader>
          <div className="space-y-3">
            <Label htmlFor="tm-kanban-title">Title</Label>
            <Input
              id="tm-kanban-title"
              placeholder="Define task..."
              value={title}
              onChange={(e) => setTitle(e.target.value)}
            />
            <Label htmlFor="tm-kanban-desc">Description</Label>
            <Textarea
              id="tm-kanban-desc"
              placeholder="Optional details..."
              value={description}
              onChange={(e) => setDescription(e.target.value)}
            />
            <div className="grid grid-cols-2 gap-2">
              <div className="space-y-2">
                <Label>Status</Label>
                <Select
                  value={createStatus}
                  onValueChange={(v) => setCreateStatus(v as TaskStatus)}
                >
                  <SelectTrigger>
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="todo">Todo</SelectItem>
                    <SelectItem value="in_progress">In Progress</SelectItem>
                    <SelectItem value="in_review">In Review</SelectItem>
                    <SelectItem value="done">Done</SelectItem>
                    <SelectItem value="blockers">Blockers</SelectItem>
                  </SelectContent>
                </Select>
              </div>
              <div className="space-y-2">
                <Label>Priority</Label>
                <Select
                  value={priority}
                  onValueChange={(v) => setPriority(v as TaskPriority)}
                >
                  <SelectTrigger>
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="low">Low</SelectItem>
                    <SelectItem value="medium">Medium</SelectItem>
                    <SelectItem value="high">High</SelectItem>
                    <SelectItem value="urgent">Urgent</SelectItem>
                  </SelectContent>
                </Select>
              </div>
            </div>
            <div className="space-y-2">
              <Label>Assignee</Label>
              <Select
                value={assigneeId ?? "unassigned"}
                onValueChange={(v) =>
                  setAssigneeId(v === "unassigned" ? undefined : v)
                }
              >
                <SelectTrigger>
                  <SelectValue placeholder="Unassigned" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="unassigned">Unassigned</SelectItem>
                  {memberDetails.map((m) => (
                    <SelectItem key={m.id} value={m.id}>
                      {m.name}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
          </div>
          <DialogFooter>
            <Button
              variant="secondary"
              onClick={handleCreateTask}
              disabled={!title.trim()}
            >
              Add Task
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </DashboardLayout>
  );
};

export default TeamMemberKanban;
