import { 
  LayoutDashboard, 
  Calendar, 
  ListTodo, 
  LayoutGrid, 
  FileText,
  Clock,
  AlertTriangle,
  CheckCircle2,
  Sparkles
} from 'lucide-react';
import DashboardLayout from '@/components/layout/DashboardLayout';
import { SidebarItem } from '@/components/layout/Sidebar';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Checkbox } from '@/components/ui/checkbox';
import { mockTasks } from '@/data/mockData';
import { formatDistanceToNow } from 'date-fns';
import { cn } from '@/lib/utils';
import { useParams } from 'react-router-dom';

const TeamMemberTasks = () => {
  const { workspaceId = "alpha" } = useParams();
  const basePath = `/business/member/workspaces/${workspaceId}`;
  const teamMemberSidebarItems: SidebarItem[] = [
    { title: 'Dashboard', href: `${basePath}/dashboard`, icon: LayoutDashboard },
    { title: 'Meetings', href: `${basePath}/meetings`, icon: Calendar },
    { title: 'My Tasks', href: `${basePath}/tasks`, icon: ListTodo, badge: 3 },
    { title: 'Kanban', href: `${basePath}/kanban`, icon: LayoutGrid },
    { title: 'Documents', href: `${basePath}/documents`, icon: FileText },
  ];
  // Filter tasks for current user (mock: using the first assignee)
  const myTasks = mockTasks.filter(t => t.assignee?.name === 'Alex Kim');
  const overdueTasks = myTasks.filter(t => t.dueDate && new Date(t.dueDate) < new Date() && t.status !== 'done');
  const pendingTasks = myTasks.filter(t => t.status !== 'done');
  const completedTasks = myTasks.filter(t => t.status === 'done');

  return (
    <DashboardLayout
      sidebarItems={teamMemberSidebarItems}
      sidebarTitle="Team Member"
      sidebarSubtitle="Personal Workspace"
      userName="Alex Kim"
      userRole="Software Engineer"
    >
      <div className="space-y-6">
        {/* Page Header */}
        <div>
          <h1 className="text-2xl font-bold">My Tasks</h1>
          <p className="text-muted-foreground">
            Tasks assigned to you from meetings
          </p>
        </div>

        {/* Stats */}
        <div className="grid grid-cols-3 gap-4">
          <Card className="shadow-card">
            <CardContent className="pt-6">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-2xl font-bold text-destructive">{overdueTasks.length}</p>
                  <p className="text-sm text-muted-foreground">Overdue</p>
                </div>
                <AlertTriangle className="h-8 w-8 text-destructive/20" />
              </div>
            </CardContent>
          </Card>
          <Card className="shadow-card">
            <CardContent className="pt-6">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-2xl font-bold text-primary">{pendingTasks.length}</p>
                  <p className="text-sm text-muted-foreground">Pending</p>
                </div>
                <Clock className="h-8 w-8 text-primary/20" />
              </div>
            </CardContent>
          </Card>
          <Card className="shadow-card">
            <CardContent className="pt-6">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-2xl font-bold text-success">{completedTasks.length}</p>
                  <p className="text-sm text-muted-foreground">Completed</p>
                </div>
                <CheckCircle2 className="h-8 w-8 text-success/20" />
              </div>
            </CardContent>
          </Card>
        </div>

        {/* Task List */}
        <Card className="shadow-card">
          <CardHeader>
            <CardTitle>All My Tasks</CardTitle>
            <CardDescription>Complete your assigned tasks</CardDescription>
          </CardHeader>
          <CardContent>
            <div className="space-y-2">
              {mockTasks.map((task) => (
                <div 
                  key={task.id} 
                  className={cn(
                    "flex items-center justify-between p-4 border rounded-lg hover:bg-muted/50",
                    task.status === 'done' && 'opacity-60'
                  )}
                >
                  <div className="flex items-center gap-4">
                    <Checkbox checked={task.status === 'done'} />
                    <div>
                      <div className="flex items-center gap-2">
                        <p className={cn(
                          "font-medium",
                          task.status === 'done' && 'line-through'
                        )}>
                          {task.title}
                        </p>
                        {task.isAutoGenerated && (
                          <Badge variant="outline" className="text-[10px] bg-secondary/10 border-secondary/30 text-secondary">
                            <Sparkles className="h-2 w-2 mr-1" />
                            AI
                          </Badge>
                        )}
                      </div>
                      <p className="text-sm text-muted-foreground">
                        {task.description}
                      </p>
                    </div>
                  </div>
                  <div className="flex items-center gap-4">
                    <Badge 
                      variant="outline" 
                      className={cn(
                        "text-xs",
                        task.priority === 'urgent' && 'border-destructive text-destructive bg-destructive/10',
                        task.priority === 'high' && 'border-warning text-warning bg-warning/10',
                        task.priority === 'medium' && 'border-primary text-primary bg-primary/10',
                        task.priority === 'low' && 'border-muted-foreground'
                      )}
                    >
                      {task.priority}
                    </Badge>
                    {task.dueDate && (
                      <span className={cn(
                        "text-sm flex items-center gap-1",
                        new Date(task.dueDate) < new Date() && task.status !== 'done'
                          ? 'text-destructive'
                          : 'text-muted-foreground'
                      )}>
                        <Clock className="h-3 w-3" />
                        {formatDistanceToNow(task.dueDate, { addSuffix: true })}
                      </span>
                    )}
                    <Badge variant="secondary" className="capitalize">
                      {task.status.replace('-', ' ')}
                    </Badge>
                  </div>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>
      </div>
    </DashboardLayout>
  );
};

export default TeamMemberTasks;
